-- EJECUTAR SOLO EN UN PROYECTO SUPABASE NUEVO DE PRUEBAS. NUNCA EN PRODUCCIÓN.
create table if not exists public.ddh_profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 email text not null unique,
 role text not null default 'user' check(role in ('user','admin')),
 status text not null default 'pending' check(status in ('pending','approved','disabled')),
 created_at timestamptz not null default now()
);
create or replace function public.ddh_validate_email() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if lower(new.email) !~ '^[^@[:space:]]+@geotec[.]cl$' then raise exception 'Solo se permiten correos @geotec.cl'; end if;
 return new;
end $$;
drop trigger if exists ddh_email_only on auth.users;
create trigger ddh_email_only before insert or update of email on auth.users for each row execute function public.ddh_validate_email();
create or replace function public.ddh_new_user() returns trigger language plpgsql security definer set search_path='' as $$
begin
 insert into public.ddh_profiles(id,email) values(new.id,lower(new.email));return new;
end $$;
drop trigger if exists ddh_create_profile on auth.users;
create trigger ddh_create_profile after insert on auth.users for each row execute function public.ddh_new_user();
create or replace function public.ddh_is_admin() returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.ddh_profiles p join auth.users u on u.id=p.id where p.id=auth.uid() and p.role='admin' and p.status='approved' and u.email_confirmed_at is not null);
$$;
create or replace function public.ddh_is_approved() returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.ddh_profiles p join auth.users u on u.id=p.id where p.id=auth.uid() and p.status='approved' and u.email_confirmed_at is not null);
$$;
revoke all on function public.ddh_is_admin() from public;
revoke all on function public.ddh_is_approved() from public;
grant execute on function public.ddh_is_admin() to authenticated;
grant execute on function public.ddh_is_approved() to authenticated;
alter table public.ddh_profiles enable row level security;
revoke all on public.ddh_profiles from anon;
grant select on public.ddh_profiles to authenticated;
drop policy if exists ddh_profile_read on public.ddh_profiles;
create policy ddh_profile_read on public.ddh_profiles for select to authenticated using(id=auth.uid() or public.ddh_is_admin());
-- Administración mediante funciones SQL; nunca conceder UPDATE directo al navegador.
create or replace function public.ddh_admin_list() returns table(id uuid,email text,role text,status text)
language sql security definer set search_path='' as $$
 select p.id,p.email,p.role,p.status from public.ddh_profiles p where public.ddh_is_admin() order by p.created_at desc;
$$;
create or replace function public.ddh_admin_set_status(target_user uuid,new_status text) returns void
language plpgsql security definer set search_path='' as $$
begin
 if not public.ddh_is_admin() then raise exception 'Acceso denegado'; end if;
 if new_status not in ('approved','disabled','pending') then raise exception 'Estado inválido'; end if;
 if target_user=auth.uid() then raise exception 'No puedes modificar tu propia cuenta'; end if;
 if exists(select 1 from public.ddh_profiles where id=target_user and role='admin') then raise exception 'No se puede modificar otro administrador desde esta función'; end if;
 update public.ddh_profiles set status=new_status where id=target_user;
end $$;
revoke all on function public.ddh_admin_list() from public;
revoke all on function public.ddh_admin_set_status(uuid,text) from public;
grant execute on function public.ddh_admin_list() to authenticated;
grant execute on function public.ddh_admin_set_status(uuid,text) to authenticated;
-- Ejecución manual únicamente por propietario del proyecto después de verificar correo.
create or replace function public.ddh_bootstrap_admin(admin_email text) returns void
language plpgsql security definer set search_path='' as $$
begin
 if current_user not in ('postgres','supabase_admin') then raise exception 'Solo SQL Editor'; end if;
 if lower(admin_email)<>'gvernal@geotec.cl' then raise exception 'Correo administrador no autorizado'; end if;
 update public.ddh_profiles p set role='admin',status='approved' from auth.users u
 where p.id=u.id and lower(u.email)=lower(admin_email) and u.email_confirmed_at is not null;
 if not found then raise exception 'Primero registra y confirma el correo administrador'; end if;
end $$;
revoke all on function public.ddh_bootstrap_admin(text) from public,anon,authenticated;
-- Historial de pruebas: estructura compatible con el código existente.
create table if not exists public.historial_operaciones (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 tipo text,fecha text,equipo text,pozo text,sector_origen text,sector_destino text,
 sector text,supervisor text,jefe_faena text,detalle text,estado text,identificador text unique
);
alter table public.historial_operaciones enable row level security;
revoke all on public.historial_operaciones from anon;
grant select,insert on public.historial_operaciones to authenticated;
grant usage,select on sequence public.historial_operaciones_id_seq to authenticated;
drop policy if exists ddh_history_read on public.historial_operaciones;
drop policy if exists ddh_history_insert on public.historial_operaciones;
create policy ddh_history_read on public.historial_operaciones for select to authenticated using(public.ddh_is_approved());
create policy ddh_history_insert on public.historial_operaciones for insert to authenticated with check(public.ddh_is_approved());
